apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: churn-classifier
  namespace: kserve
spec:
  predictor:
    containers:
    - name: kserve-container
      image: churn-classifier:v8
      ports:
        - containerPort: 8080
          protocol: TCP
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"